# 社区第三方预编译软件包源 (涵盖 kenzok8 / passwall / 常用插件)
src/gz community_kiddin9 https://dl.openwrt.ai/packages-24.10/aarch64_generic/kiddin9
src/gz community_cortex_a53 https://dl.openwrt.ai/packages-24.10/aarch64_cortex-a53/kiddin9
